import type { Metadata } from "next";
import { Inter} from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navigation";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

const interMono = Inter({
  variable: "--font-inter-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next-auth-cata",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interSans.variable}  antialiased`}
      >
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
